---
title: "Homework 3 Solutions"
format: 
  html:
    embed-resources: true
editor: source
author: "Ciaran Evans"
---

#### Question 1

```{r}
huber <- function(x){
  return(ifelse(abs(x) <= 1, x^2, 2*abs(x) - 1))
}
```

#### Question 2

```{r}
huber(c(0.5, 1, 2))
```

#### Question 3

```{r}
huber <- function(x, a=1){
  return(ifelse(abs(x) <= a, x^2, 2*a*abs(x) - a^2))
}
```

#### Question 4

```{r}
relu <- function(x){
  return(ifelse(x > 0, x, 0))
}

relu(c(-1, 1))
```

#### Question 5

```{r}
leaky_relu <- function(x, a=0){
  return(ifelse(x > 0, x, a*x))
}
```


#### Question 6

```{r}
test_power <- function(n, nsim, beta0, beta1, alpha = 0.05){
  
  pvals <- rep(NA, nsim)
  
  for(i in 1:nsim){
    x <- runif(n, min=0, max=1)
    noise <- rnorm(n, mean=0, sd=1)
    y <- beta0 + beta1*x + noise
    
    lm_mod <- lm(y ~ x)
    pvals[i] <- summary(lm_mod)$coefficients[2,4]
  }
  
  return(mean(pvals < alpha))
}
```


#### Question 7

```{r}
test_power(100, 1000, 0, 0, 0.05)
test_power(100, 1000, 0, -1, 0.05)
test_power(100, 1000, 0, -0.5, 0.05)
test_power(100, 1000, 0, 0.5, 0.05)
test_power(100, 1000, 0, 1, 0.05)
```

Holding other simulation settings fixed, power increases as $\beta_1$ moves further away from 0, because the difference between the null and alternative hypotheses is larger.

#### Question 8

```{r}
test_power(10, 1000, 0, 0.5, 0.05)
test_power(50, 1000, 0, 0.5, 0.05)
test_power(100, 1000, 0, 0.5, 0.05)
test_power(500, 1000, 0, 0.5, 0.05)
```

Power increases as sample size increases, because there is less variability in our estimation of $\beta_1$.

