---
title: "Homework 7 solutions"
format: 
  html:
    embed-resources: true
editor: source
author: "Ciaran Evans"
---


#### Question 1

```{r}
df1 <- data.frame(
  grp = c("A", "A", "B", "B"),
  sex = c("F", "M", "F", "M"),
  meanL = c(0.225, 0.47, 0.325, 0.547),
  sdL = c(0.106, 0.325, 0.106, 0.308),
  meanR = c(0.34, 0.57, 0.4, 0.647),
  sdR = c(0.0849, 0.325, 0.0707, 0.274)
)
```

```{python}
import pandas as pd

df1 = r.df1

(df1.melt(id_vars = ['grp', 'sex'], var_name = 'stat')
    .pivot(columns = ['sex', 'stat'], values = 'value',
           index = 'grp'))
```

#### Question 2

```{r}
df2 <- data.frame(id = rep(c(1, 2, 3), 2),
                  group = rep(c("T", "C"), each=3),
                  vals = c(4, 6, 8, 5, 6, 10))
```

```{python}
df2 = r.df2

df2_new = df2.pivot(index = 'id', columns = 'group', values = 'vals')
df2_new = df2_new.assign(diff = df2_new['T'] - df2_new['C'])
df2_new
```

#### Question 3

```{python}
sim_results = pd.read_csv("https://sta279-f23.github.io/homework/sim_results.csv")
```

```{python}
sim_results.melt(id_vars = 'n', var_name = 'method', value_name = 'result')
```

#### Question 4

```{python}
sim_res_new = sim_results.melt(id_vars = 'n', var_name = 'method', value_name = 'result')
sim_res_new[['method', 'iteration']] = sim_res_new['method'].str.split('_', expand=True)
sim_res_new
```

#### Question 5

```{python}
import numpy as np

sim_res_new = (sim_res_new.groupby(by=['n', 'method'])
            .agg(coverage = ('result', lambda x: np.mean(2 - x))))
sim_res_new
```

#### Question 6

```{python}
sim_res_new = sim_res_new.reset_index()
sim_res_new
```

#### Question 7

```{python}
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure()
sns.lineplot(x="n", y="coverage", data=sim_res_new, hue="method", marker ='o')
plt.show()
```

#### Question 8

```{r}
months <- tolower(lubridate::month(c(12, 1:7), label=T, abbr=F))
months
```

#### Question 9

```{r}
urls <- paste0("https://www.basketball-reference.com/leagues/NBA_2021_games-",
               months, ".html")
```

#### Question 10

```{r}
library(rvest)
library(tidyverse)

df_list <- list()

for(i in 1:length(urls)){
  df_list[[i]] <- read_html(urls[i]) |>
    html_element("table") |>
    html_table(header = TRUE, fill = TRUE)
}

df_list[[1]]
df_list[[2]]
```

#### Question 11

```{r, message=F, warning=F}
library(data.table)

nba <- rbindlist(df_list)
```

#### Question 12

```{r, message=F, warning=F}
colnames(nba) <- c("date", "start", "visitor", "visitor_pts", "home", "home_pts",
                   "v1", "v2", "attend", "arena", "notes")

nba <- nba |>
  mutate(attend = as.numeric(gsub(",", "", attend)))

nba |>
  mutate(diff = home_pts - visitor_pts) |>
  ggplot(aes(x = attend, y = diff)) +
  geom_point() +
  geom_smooth() +
  theme_bw() +
  labs(x = "Attendance", y = "Home pts - away pts")
```

#### Question 13

```{r}
nba |>
  mutate(month = tolower(lubridate::month(lubridate::mdy(date), 
                                          label=T, abbr=F))) |>
  mutate(month = factor(month, levels = months)) |>
  group_by(month) |>
  summarize(frac_0 = mean(attend == 0, na.rm=T)) |>
  ggplot(aes(x = month, y = frac_0)) +
  geom_point() +
  theme_bw() +
  labs(x = "Month", y = "Fraction of games with 0 attendees")
```




