---
title: "Class Project"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

# Overview

The final project for STA 279 is meant to bring together several important topics from the course, with an emphasis on data wrangling and non-tabular data. Your project is meant to answer a question using data. You will:

* Propose a research question of interest (e.g., how has scoring on Taskmaster changed over the course of the series?)
* Identify at least two sources of data to answer this research question. At least one of these data sources cannot already be in tabular form.
* Wrangle the data needed to answer your research question.
* Address your research question with some combination of summary statistics, visualizations, and statistical models (you are welcome to use models learned outside of STA 279)

# Requirements and rules

* You may not use any of the data sources previously used for homework assignments or class activities in this course
* One of your data sources must be (originally) non-tabular. Tabular data scraped from a webpage (e.g. Wikipedia, Basketball reference, etc.) still counts as tabular data! Examples of non-tabular data include scraping the episode titles from the Bakeoff Wikipedia articles, the contestant ages from the Taskmaster site, extracting text from an article, etc. (It is ok if you scrape non-tabular data and later create your own table with it)
* This project *must* be completed individually. You may not work with other students in any way, or share any code or help.
* You are welcome to use the class resources and textbooks. You may also use the internet (Stack Exchange, Stack Overflow, etc.) for guidance on small pieces of your code. 
* You may not use Chat GPT or other AI tools for any part of this project. 
* You may not borrow or copy any large pieces of code from the internet. For example, finding an existing web scraping project on the internet would be plagiarism

Any violations of these rules will result in a 0 on the project.

# Deliverables

* Project checkpoint (brief overview of your research questions and data sources). **Due:** Friday, April 19 at 2pm on Canvas
* Final project report (2-3 page summary of your research question, data, and results), and all code used. **Due:** Tuesday, April 30 at 2pm on Canvas

## Project checkpoint

Identify a data context that interests you, and find two data sources related to that context. (For example, you might scrape details about every Taylor Swift song and use regular expressions to format the information in a way that allows easy question asking). Then create a research question about your data context which can be answered using your data sources.

Note that this is deliberately open ended! Pick something that is interesting to you personally.

Submit a short document on Canvas describing the data context, data sources, and research question, and how you will answer that research question.

## Final project report

Use your data sources to answer the research question. Importing the data sources in a form that allows you to answer the research question may involve a variety of data wrangling, web scraping, and regular expressions to extract pertinent information.

Answering the research question could involve visualizations, summary statistics, and/or statistical models and tests. If you have a technique from another course that you would like to implement here (e.g. a GLM from 214, a random forest from 363, some dimension reduction from 362, etc.) you are welcome, but not required, to try it.

When you are done, create a 2-3 page document that describes your data sources, research question, and results. Do **not** include any code in this document! However, you can include figures, tables, and model results.

Finally, submit a separate file (.Rmd, .qmd, or .R) which contains all the code used in your analysis.



