---
title: "Class activity solutions"
format: html
editor: source
author: "Ciaran Evans"
---


```{r, message=F, warning=F}
library(tidyverse)
library(googlesheets4)
gs4_deauth()
gdp_data <- read_sheet("https://docs.google.com/spreadsheets/d/1RctTQmKB0hzbm1E8rGcufYdMshRdhmYdeL29nXqmvsc/pub?gid=0")
lit_data = read_sheet("https://docs.google.com/spreadsheets/d/1hDinTIRHQIaZg1RUn6Z_6mo12PtKwEPFIz_mJVF6P5I/pub?gid=0")
```

```{r}
gdp_data <- gdp_data |>
  rename(country = starts_with("Income")) |>
  pivot_longer(-country, names_to = "year", values_to = "gdp",
               values_drop_na = TRUE)

lit_data <- lit_data |>
  rename(country = starts_with("Adult")) |>
  pivot_longer(-country, names_to = "year", values_to = "literacy",
               values_drop_na = TRUE)
```

1.

```{r}
lit_gdp <- lit_data |>
  inner_join(gdp_data, join_by(country, year))
```

2. 

In R:

```{r}
air_quality <- read.csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_long.csv")
air_parameters <- read.csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_parameters.csv")

air_quality <- air_quality |>
  left_join(air_parameters, join_by(parameter == id))

head(air_quality)
```

In Python:

```{python}
import pandas as pd

air_quality = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_long.csv")
air_parameters = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_parameters.csv")

air_quality = pd.merge(air_quality, air_parameters, how = 'left',  
                       left_on = 'parameter', right_on = 'id')
air_quality.head()
```

3.

```{r}
library(nycflights13)

flights |>
  left_join(planes, join_by(tailnum)) |>
  head()
```

4.

```{r}
flights |>
  left_join(planes, join_by(tailnum)) |>
  rename(manufacture_date = year.y) |>
  select(tailnum, manufacture_date) |>
  distinct() |>
  slice_min(manufacture_date, n=3)
```

The oldest plane has tail number N381AA.

