---
title: "Class activity solutions"
format: html
editor: source
author: "Ciaran Evans"
---

1.

```{r}
x1 <- list(c(2, 7, 9))
x1[[1]]

x2 <- list(list(c(2, 7, 9)))
x2[[1]][[1]]

x3 <- list(c(2, 7, 9), list("a", "b"))
x3[[1]]

x4 <- list(c("a", "b"), list(list(c(2, 7, 9))))
x4[[2]][[1]][[1]]
```

2.

```{r}
x5 <- list("a", "b", list("c", list(c(2, 7, 9))))
x5[[3]][[2]][[1]]
```


3.

```{r}
assess_coverage <- function(n, nsim, beta0, beta1, noise_dist){
  results <- rep(NA, nsim)

  for(i in 1:nsim){
    x <- runif(n, min=0, max=1)
    noise <- noise_dist(n)
    y <- beta0 + beta1*x + noise

    lm_mod <- lm(y ~ x)
    ci <- confint(lm_mod, "x", level = 0.95)
    results[i] <- ci[1] < beta1 & ci[2] > beta1
  }
  return(mean(results))
}

chisq_1 <- function(m){
  return(rchisq(m, df=1))
}

dist_funs <- list(rexp, rnorm, chisq_1)

obs_coverage <- rep(NA, length(dist_funs))

for(i in 1:length(obs_coverage)){
  obs_coverage[i] <- assess_coverage(n=100, nsim = 1000, beta0 = 0, beta1 = 1,
                                     noise_dist = dist_funs[[i]])
}

obs_coverage
```

